name: PR Extensions builds
on: [pull_request, workflow_dispatch]

env:
  COINBASE_APP_ID: ${{ secrets.COINBASE_APP_ID }}
  MOONPAY_API_KEY: ${{ secrets.MOONPAY_API_KEY }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SEGMENT_WRITE_KEY: ${{ secrets.SEGMENT_WRITE_KEY_STAGING }}
  TRANSAK_API_KEY: ${{ secrets.TRANSAK_API_KEY }}
  WALLET_ENVIRONMENT: feature

jobs:
  pre-run:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@ad6cb1b847ffb509a69b745b6ee2f1d14dfe14b8
        with:
          access_token: ${{ github.token }}

  update-pull-request-body:
    name: Add links to built extensions
    if: github.repository == 'leather-wallet/extension' && github.actor != 'dependabot[bot]'
    runs-on: ubuntu-latest
    needs:
      - pre-run
    steps:
      - uses: kyranjamie/pull-request-fixed-header@v1.0.1
        with:
          header: '> Try out this version of Leather — download [extension builds](https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}).'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build_chrome_extension:
    name: Build debug Chrome extension
    runs-on: ubuntu-latest
    needs:
      - pre-run
    steps:
      - uses: actions/checkout@v4

      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: ./.github/actions/provision

      - name: Build project
        run: yarn build

      - name: Build extension
        run: sh build-ext.sh

      - uses: actions/upload-artifact@v3
        name: Upload Chrome Extension Zip
        with:
          name: stacks-wallet-chromium
          path: leather-chromium.zip

  build_firefox:
    name: Build debug Firefox extension
    runs-on: ubuntu-latest
    needs:
      - pre-run
    env:
      TARGET_BROWSER: firefox
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - uses: actions/cache@v3
        id: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/package.json') }}

      - uses: ./.github/actions/provision

      - name: Build project
        run: yarn build

      - name: Build extension
        run: sh build-ext.sh

      - name: Rename file
        run: mv leather-chromium.zip leather-firefox.zip

      - uses: actions/upload-artifact@v3
        with:
          name: stacks-wallet-firefox
          path: leather-firefox.zip
